### ISSUE TITLE
RabbitMQ: Channel Selection - Send Discord Message (Bot)

### ISSUE THREAD

**Issue by cyri113** [RnDAO/pulseSurvey#96]
In reference to: 
https://www.notion.so/channel-selection-connected-to-data-shown-in-line-graphs-and-heatmap-c3d454ad0ea140649728ea0b62a1c4d8?pvs=4

This should be implemented as per the following diagram:
https://miro.com/app/board/uXjVMPYA244=/?share_link_id=123845624136

**Tasks:**
- [ ] Listen for `discord.analysis.completed` event
- [ ] Send discord message to user

**Open Questions**
- [ ] Should it be public or private? 
- [ ] In which channel should the message be sent to?
- [ ] Should we send a DM if the users DM is open?

**Comment by cyri113** [comment]
Deprecated in favour of https://github.com/RnDAO/tc-discordBot
